// Glossary of stat abbreviations shown around Player Data.
// Keep entries short — these render inside a tooltip.

export const STAT_GLOSSARY: Record<string, string> = {
  // Hitting
  AVG: "Batting Average — Hits ÷ At-Bats.",
  OBP: "On-Base Percentage — (Hits + Walks + HBP) ÷ Plate Appearances.",
  SLG: "Slugging — Total Bases ÷ At-Bats.",
  OPS: "On-Base + Slugging.",
  wOBA: "Weighted On-Base Average — Weights outcomes based on run expectancy.",
  xSLG: "Expected Slugging — Based on exit velocity and launch angle.",
  "Avg EV": "Average Exit Velocity on batted balls (mph).",
  "Whiff%": "Swings and misses ÷ Total Swings.",
  "Swing%": "Pitches swung at ÷ Total pitches seen.",
  "O-Swing%": "Swings at pitches outside the strike zone ÷ Pitches outside the zone.",
  "P/PA": "Pitches per Plate Appearance.",
  "IZ Whiff%": "In-Zone Whiff% — Swings & misses on pitches in the strike zone ÷ in-zone swings.",
  "BA vs Stuff+>100": "Batting Average against pitches with a Stuff+ rating above 100 (above league average).",
  "Hard Contact %": "Batted balls with exit velocity ≥ 95 mph ÷ All batted balls.",
  "Whiff Rate / 100": "Whiff Rate vs pitches with Stuff+ ≥ 100.",
  PAs: "Plate Appearances.",
  Hits: "Total Hits.",
  HRs: "Home Runs.",
  "Barrel%": "Barrels ÷ Batted Balls. Barrel = optimal contact (EV ≥ 98 mph with launch angle 26°-30°, expanding range as EV increases).",
  "Sweet Spot%": "Batted balls with launch angle between 8° and 32° ÷ All batted balls.",
  "Z-Swing%": "Swings on pitches inside the strike zone ÷ Pitches inside the zone.",
  ISO: "Isolated Power — SLG − AVG. Measures raw power independent of singles.",

  // Pitching
  "Opp AVG": "Opponent Batting Average — Hits allowed ÷ At-Bats faced.",
  "K%": "Strikeout Rate — Strikeouts ÷ Plate Appearances.",
  "BB%": "Walk Rate — Walks ÷ Plate Appearances.",
  "Avg FB Velo": "Average Fastball Velocity (Four-Seam, Sinker, Fastball).",
  "Zone%": "Pitches in the strike zone ÷ Total pitches.",
  "CSW%": "Called Strikes + Whiffs ÷ Total pitches. Industry standard for pitch quality.",
  "FPS%": "First-Pitch Strike% — 0-0 pitches resulting in a strike ÷ Total 0-0 pitches.",
  "Chase%": "Pitches outside the zone that were swung at ÷ Pitches outside the zone.",
  "Total BF": "Total Batters Faced.",
  Strikeouts: "Total Strikeouts.",
  Walks: "Total Walks.",
  WHIP: "Walks + Hits per Inning Pitched. (BB + H) ÷ IP. Lower is better.",
  "K/BB": "Strikeout-to-Walk Ratio — Strikeouts ÷ Walks.",
  "K/9": "Strikeouts per 9 innings pitched.",
  "BB/9": "Walks per 9 innings pitched.",
  "GB%": "Ground Ball% — Ground balls ÷ Batted balls of this pitch type.",
  "FB%": "Fly Ball% — Fly balls (incl. popups) ÷ Batted balls of this pitch type.",
  "LD%": "Line Drive% — Line drives ÷ Batted balls of this pitch type.",

  // Pitch type table columns
  "Usage%": "Pitches of this type ÷ Total pitches thrown.",
  IVB: "Induced Vertical Break — vertical movement excluding gravity (inches).",
  HB: "Horizontal Break (inches).",
  VAA: "Vertical Approach Angle at home plate (degrees).",
  HAA: "Horizontal Approach Angle at home plate (degrees).",
  "Rel Height": "Release Height — height of the ball at release (feet).",
  Extension: "Distance toward the plate at release (feet). More extension = effective velo boost.",
  "Stuff+": "K-State proprietary model. 100 = league average. Weighted z-scores of velo, spin, IVB, HB, VAA, extension vs league baselines.",
  Whiffs: "Total swings and misses on this pitch.",
  "# of Pitches": "Total count of this pitch type thrown.",
  "Avg Velo": "Average release velocity (mph).",
  "Max Velo": "Maximum release velocity (mph).",
  "Spin Rate": "Average spin rate (rpm).",
};
